team_assignments:
  "apollo": "blue"

quad_state_topics:
  "apollo": "/apollo/state"

proposed_trajectory_topics:
  "apollo": "/apollo/proposed_trajectory"

updated_trajectory_topics:
  "apollo": "/apollo/updated_trajectory"

visualization_trajectory_topics:
  "apollo": "/apollo/visualization_trajectory"

balloon_status_topics:
  "red": "/game_engine/red_balloon_status"
  "blue": "/game_engine/blue_balloon_status"

goal_status_topics:
  "home": "/game_engine/home_status"

map_file_path: "/home/aerial-robotics/Workspace/game-engine/resources/maps/temple.map"
quad_mesh_file_path: "file:///home/aerial-robotics/Workspace/game-engine/resources/meshes/quad.stl"
balloon_mesh_file_path: "file:///home/aerial-robotics/Workspace/game-engine/resources/meshes/balloon.stl"
goal_mesh_file_path: "file:///home/aerial-robotics/Workspace/game-engine/resources/meshes/torus.stl"

blue_balloon_position: [-19.0, 17.0, -4.0]
red_balloon_position:  [-26.0, 17.0, 0.0]

move_blue: false
blue_balloon_position_new: [-26.0, 17.0, 0.0]
blue_balloon_max_move_time: 60.0

move_red: false
red_balloon_position_new:  [-19.0, 17.0, -4.0]
red_balloon_max_move_time: 60.0

use_seed: true
seed: 31

# 0: zero, 1: mild, 2: stiff, 3: intense, 4: ludicrous
wind_intensity: 2

goal_position: [-12.0, 17.0, -4.0]

initial_quad_positions:
  "apollo": "-12.0 17.0 -4.0"


