team_assignments:
  "apollo": "blue"

quad_state_topics:
  "apollo": "/apollo/state"

proposed_trajectory_topics:
  "apollo": "/apollo/proposed_trajectory"

updated_trajectory_topics:
  "apollo": "/apollo/updated_trajectory"

visualization_trajectory_topics:
  "apollo": "/apollo/visualization_trajectory"

balloon_status_topics:
  "red": "/game_engine/red_balloon_status"
  "blue": "/game_engine/blue_balloon_status"

goal_status_topics:
  "home": "/game_engine/home_status"

map_file_path: "/home/aerial-robotics/Workspace/game-engine/resources/maps/tournament.map"
quad_mesh_file_path: "file:///home/aerial-robotics/Workspace/game-engine/resources/meshes/quad.stl"
balloon_mesh_file_path: "file:///home/aerial-robotics/Workspace/game-engine/resources/meshes/balloon.stl"
goal_mesh_file_path: "file:///home/aerial-robotics/Workspace/game-engine/resources/meshes/torus.stl"

blue_balloon_position: [-16.0, 19.0, -4.0]
red_balloon_position:  [-23.0, 17.0, -2.0]

move_blue: false
blue_balloon_position_new: [-21.0, 19.0, -4.0]
blue_balloon_max_move_time: 60.0

move_red: false
red_balloon_position_new:  [-24.0, 20.0, -3.5]
red_balloon_max_move_time: 60.0

use_seed: true
seed: 0

# 0: zero, 1: mild, 2: stiff, 3: intense, 4: ludicrous
wind_intensity: 2

goal_position: [-13.0, 16.0, -4.0]

initial_quad_positions:
  "apollo": "-13.0 16.0 -4.0"

