team_assignments:
  "phoenix": "blue"

quad_state_topics:
  "phoenix": "/phoenix/state"

proposed_trajectory_topics:
  "phoenix": "/phoenix/proposed_trajectory"

updated_trajectory_topics:
  "phoenix": "/phoenix/updated_trajectory"

balloon_status_topics:
  "red": "/game_engine/red_balloon_status"
  "blue": "/game_engine/blue_balloon_status"

map_file_path: "/home/aerial-robotics/Workspace/game-engine/resources/maps/forest.map"
quad_mesh_file_path: "file:///home/aerial-robotics/Workspace/game-engine/resources/meshes/quad.stl"
balloon_mesh_file_path: "file:///home/aerial-robotics/Workspace/game-engine/resources/meshes/balloon.stl"

blue_balloon_position: [-16.0, 19.0, -4.0]
red_balloon_position:  [-26.0, 15.0, 0.0]

move_blue: true
blue_balloon_position_new: [-21.0, 19.0, -4.0]
blue_balloon_max_move_time: 60.0

move_red: true
red_balloon_position_new:  [-24.0, 20.0, -3.5]
red_balloon_max_move_time: 60.0

use_seed: true
seed: 0

initial_quad_positions:
  "phoenix": "-12.0 14.0 -4.0"


